---
title: "1-1 데이터의 분류"
output: html_notebook
---

# 1-1 데이터의 분류

데이터의 종류에는 어떤 것들이 있는지 정리해봅니다.

## 0. 데이터셋 소개

### Titanic

[Titanic](https://www.kaggle.com/competitions/titanic/data) 탑승객의 생존 유무를 담은 데이터셋 입니다.

| Data        | Description                                 | Dictionary                                     |
|:------------|:--------------------------------------------|:-----------------------------------------------|
| PassengerId | Passenger Id, Index                         |                                                |
| Survived    | Survival                                    | 0 = No, 1 = Yes                                |
| Pclass      | Ticket class                                | 1 = 1st, 2 = 2nd, 3 = 3rd                      |
| Name        | Name                                        |                                                |
| Sex         | Sex                                         |                                                |
| Age         | Age in years                                |                                                |
| Sibsp       | \# of siblings / spouses aboard the Titanic |                                                |
| Parch       | \# of parents / children aboard the Titanic |                                                |
| Ticket      | Ticket number                               |                                                |
| Fare        | Passenger fare                              |                                                |
| Cabin       | Cabin number                                |                                                |
| Embarked    | Port of Embarkation                         | C = Cherbourg, Q = Queenstown, S = Southampton |

다양한 형식의 데이터를 가지고 있으며, 여러 가지 아이디어를 생각하고 시도할 만한 요소가 많게끔 기획된 데이터셋입니다.

```{r}
# readr 패키지 로드
library(readr)

# 데이터 읽기
df_titanic <- read_csv('../data/titanic.csv', col_types = cols())
```

## 1.데이터의 종류

### 정형 데이터(Structured Data)

-   구조화된 형식을 가지며, 행과 열로 이루어진 표 형태를 이룹니다. 열(Column)은 특정 유형의 데이터를 포함하고, 행(Row)은 고유한 레코드를 나타냅니다.

    ```         
    Ex) CSV 파일. 관계형 DB의 테이블, ...
    ```

#### 정형 데이터의 분류

1.  질적 데이터(Qualitative data): 품질, 특성 또는 특성의 유무를 나타내는 비수치적 데이터입니다. 범주형 데이터라고도 불립니다. 수학적 계산이 가능하더라도 의미는 없습니다.

::: {style="padding: 5px; margin-left: 15px;"}
-   명목형 데이터(nominal data): 순서의 개념이 없습니다. Ex) 색상, 국가

-   서열형 데이터(ordinal data): 순서의 개념이 있습니다. Ex) 직급, 난이도
:::

2.  양적 데이터(Quantitative data): 양이나 수치를 나타낼 수 있는 데이터로, 수학적 계산이 가능한 데이터입니다.

::: {style="padding: 5px; margin-left: 15px;"}
-   연속형 데이터(continuous data): 실수와 같은 연속적인 수치를 나타내는 데이터입니다. Ex) 키, 무게, 온도

-   이산형 자료(discrete data): 정수와 같이 불연속적인 수치를 나타내는 데이터입니다. Ex) 출석 인원수, 무사고 일수
:::

**[Ex.1]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic의 질적 데이터들을 살펴봅니다.
:::

```{R}
library(dplyr)

# 질적 데이터의 수준들을 가져옵니다.
qualitative_columns <- df_titanic %>% select(Survived, Pclass, Sex, Embarked)

# 각 열에 대한 연산을 수행하게 합니다.
unique_levels <- lapply(qualitative_columns, function(x) unique(na.omit(x)))

# 결과를 리스트로 출력
unique_levels
```

Survived, Sex, Embarked는 명목형 데이터이고, Pclass는 서열형 데이터입니다.

```{R}
# PassengerId는 정수형이지만 명목형 데이터입니다.사칙연산이 성립하지 않습니다.
# (PassengerId 1 + PassengerId 2 ≠ PassengerId 3)
head(df_titanic$PassengerId)
```

Cabin은 명목형 데이터와 정수형 데이터가 결합되어 있고 단일 객체를 나타내는 것이 아닌 복수의 객체를 나타내도록 되어 있습니다.

C85, B53 B55, ...

**[Ex.2]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic의 양적 데이터를 살펴봅니다.
:::

```{R}
# 수치를 나타내는 정수형 데이터입니다. 
head( df_titanic %>% select(Age, SibSp, Parch))
```

```{R}
head(df_titanic$Fare)
```

**[Ex.3]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
Cabin의 첫자리는 객실 유형을 그 다음 숫자는 객실의 위치를 나타냅니다.

결측이 아닌 Cabin만을 뽑고,객실 유형을 분리하여 Cabin_Type 변수를 만들고,

객실 위치를 분리하여 Cabin_No 변수를 만듭니다.
:::

```{R}
# Cabin 열에서 결측값이 아닌 행을 선택하고, 고유 값 추출
unique_cabins <- df_titanic %>% 
  filter(!is.na(Cabin)) %>% 
  pull(Cabin) %>% 
  unique()

# 결과 출력 (옵션)
print(unique_cabins)
```

```{R}
library(tidyr)

# Cabin 열에서 결측값이 아닌 행을 선택하고, 공백으로 분할 후 각 값을 분리하여 새로운 열로 나눕니다
df_titanic %>%
  filter(!is.na(Cabin)) %>%
  mutate(Cabin_Split = strsplit(as.character(Cabin), ' ')) %>%
  unnest(Cabin_Split) %>%
  mutate(
    Cabin_Type = substr(Cabin_Split, 1, 1),
    Cabin_No = substr(Cabin_Split, 2, nchar(Cabin_Split))
  ) %>%
  select(Cabin_Type, Cabin_No)
```

#### 반정형 데이터(Semi-Structured Data)

-   일정한 형식을 지니고 있지만 완전한 정형 데이터는 아닌 데이터입니다.

XML

``` xml
<person>
 <name>John Doe</name>
 <age>30</age>
 <address>
   <city>New York</city>
   <zipcode>10001</zipcode>
 </address>
 <contacts>
   <email>john.doe@example.com</email>
   <phone>123-456-7890</phone>
 </contacts>
</person>
```

JSON

``` json
{
  "person": {
    "name": "John Doe",
    "age": 30,
    "address": {
      "city": "New York",
      "zipcode": "10001"
    },
    "contacts": {
      "email": "john.doe@example.com",
      "phone": "123-456-7890"
    }
  }
}
```

## 2. 정형 데이터의 구성 요소

### Series

-   **1**차원의 **인덱스**가 부여된 자료 저장 공간

    -   **인덱스**(Index): 요소에 부여된 색인 데이터

```{R}
# 벡터 생성
s <- c(a = 1, b = 5, c = 3, d = 10, e = 7)

# 벡터 출력
print(s)
```

```{R}
# 'a', 'd' 의 값을 가져오기
s[c('a', 'd')]
```

### DataFrame

-   **2**차원의 **인덱스**가 부여된 자료 저장 공간.

1.  인덱스(Index): 행(row)에 부여된 색인 데이터

2.  컬럼(Column): 열(column)에 부여된 색인 데이터

## 3. 빅데이터

### 3V (Volume, Velocity, Variety)

1.  Volume(양) : 데이터의 규모나 양을 나타냅니다.

2.  Velocity(속도): 데이터가 생성, 수집, 그리고 분석되는 속도를 나타냅니다.

3.  Variety(다양성): 데이터 형식의 다양함을 나타냅니다.

### 5V (3V + Veracity, Value)

4.  Veracity(정확성) : 데이터의 정확성과 신뢰성을 나타냅니다.

5.  Value(가치): 데이터를 통해 얻을 수 있는 가치를 나타냅니다.

## 4. 모델

-   **모델**(모형)의 사전적 의미: 대상을 근사화한 객체

-   통계 / 머신 러닝 관점에서의 의미

    데이터의 근사화 → 데이터에 드러난 패턴/지식을 근사화한 객체
