---
title: "1-3 데이터 변환"
output: html_notebook
---

# 1-3 데이터 변환

## 0. 데이터셋 소개

### Titanic

[Titanic](https://www.kaggle.com/competitions/titanic/data) 탑승객의 생존 유무를 담은 데이터셋 입니다.

| Data        | Description                                 | Dictionary                                     |
|:------------|:--------------------------------------------|:-----------------------------------------------|
| PassengerId | Passenger Id, Index                         |                                                |
| Survived    | Survival                                    | 0 = No, 1 = Yes                                |
| Pclass      | Ticket class                                | 1 = 1st, 2 = 2nd, 3 = 3rd                      |
| Name        | Name                                        |                                                |
| Sex         | Sex                                         |                                                |
| Age         | Age in years                                |                                                |
| Sibsp       | \# of siblings / spouses aboard the Titanic |                                                |
| Parch       | \# of parents / children aboard the Titanic |                                                |
| Ticket      | Ticket number                               |                                                |
| Fare        | Passenger fare                              |                                                |
| Cabin       | Cabin number                                |                                                |
| Embarked    | Port of Embarkation                         | C = Cherbourg, Q = Queenstown, S = Southampton |

다양한 형식의 데이터를 가지고 있으며, 여러 가지 아이디어를 생각하고 시도할 만한 요소가 많게끔 기획된 데이터셋입니다.

```{r}
# readr 패키지 로드
library(readr)
library(dplyr)
library(tidyr)

# 데이터 읽기
df_titanic <- read_csv('../data/titanic.csv', col_types = cols())
df_titanic
```

## 1. 수치형 데이터

### 정규화(Normalize)

변수의 최소값을 0, 최대값이 1이 되도록 변환합니다.

> $X_{new} = \frac{X - min(X)}{max(X) - min(X)}$

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
**sklearn.preprocessing.MinMaxScaler**

**주요 파라메터**

| 파라메터명    | 기능                          |
|---------------|-------------------------------|
| feature_range | (최소값, 최대값) 형태의 tuple |
:::

**[Ex.1]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic에서 Age와 Fare의 최소값은 0, 최대값이 1이 되도록 변환합니다.

그리고 변환된 값을 변수명 뒤에 '\_n'을 붙여 Age_n, Fare_n으로 저장합니다.
:::

```{R}
library(caret)

# 정규화 대상 컬럼
mm_cols <- c('Age', 'Fare')

# 정규화 변환을 합니다.
preProcValues <- preProcess(df_titanic[, mm_cols], method = c("range"))

print(preProcValues)
```

```{R}
mm_cols_n <- paste0(mm_cols, "_n")
df_titanic[mm_cols_n] <- predict(preProcValues, df_titanic[, mm_cols])
head(df_titanic[mm_cols_n])
```

```{R}
df_titanic %>%
  summarise(across(all_of(mm_cols_n), list(min = min, max = max), na.rm = TRUE))
```

**[Ex.2]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic에서 Age와 Fare의 최소값은 -1, 최대값이 1이 되도록 변환합니다.

그리고 변환된 값을 변수명 뒤에 '\_n'을 붙여 Age_n, Fare_n으로 저장합니다.
:::

```{R}
# 정규화 대상 컬럼
mm_cols <- c('Age', 'Fare')

# Min-Max Scaling을 -1에서 1로 설정
range <- c(-1, 1)
preProcValues <- preProcess(df_titanic[, mm_cols], method = c("range"), 
                            rangeBounds = range)

# 정규화된 컬럼의 이름을 변경합니다.
mm_cols_n <- paste0(mm_cols, "_n")

# 정규화된 데이터를 변환하여 추가합니다.
df_titanic[mm_cols_n] <- predict(preProcValues, df_titanic[, mm_cols])

# 각 컬럼의 최소값과 최대값을 계산
df_titanic %>%
  summarise(across(all_of(mm_cols_n), list(min = ~ min(., na.rm = TRUE), max = ~ max(., na.rm = TRUE))))
```

### 표준화(Standardize)

-   변수의 평균이 0, 표준편차가 1이 되도록 변환합니다.

> \$X\_{std}= \frac{X - \mu}{\sigma} \$

**[Ex.3]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic에서 Age와 Fare를 표준화합니다.

그리고 변환된 값을 변수명 뒤에 '\_s'을 붙여 Age_s, Fare_s으로 저장합니다.
:::

```{R}
# 표준화 대상 컬럼
std_cols <- c('Age', 'Fare')

# 표준화된 컬럼의 이름
std_cols_s <- paste0(std_cols, "_s")

# 표준화 변환기를 학습하고 변환값을 뽑아냅니다
preProcValues <- preProcess(df_titanic[, std_cols], method = c("center", "scale"))

# 표준화된 데이터를 변환하여 추가합니다.
df_titanic[std_cols_s] <- predict(preProcValues, df_titanic[, std_cols])

df_titanic %>%
  summarise(across(all_of(std_cols_s), list(mean = ~ mean(., na.rm = TRUE), std = ~ sd(., na.rm = TRUE))))
```

**정규화와 표준화의 효과**

-   회귀 분석시 정규화와 표준화를 통해 변수의 스케일을 균일화하여, 독립변수가 종속변수에 미치는 정도를 파악하기 쉽게 합니다.

-   Ridge와 Lasso와 같은 모수의 크기에 대해 제약을 가하는 모델에서 규제가 균일하게 적용되도록 합니다.

-   Gradient Descent와 같은 공간 탐색 기반의 알고리즘에서 학습률과 변수들간의 영향이 균일하도록 합니다.

### 거듭제곱 변환(Power Transformation)

-   변수의 분포를 우측 또는 좌측으로 치우친 정도를 조정합니다.

-   거듭수를 나타내는 파라메터 $\lambda$에 따라 변환함수가 달라집니다.

| $$\lambda$$       | 거듭 제곱 함수            |
|-------------------|---------------------------|
| $$\lambda \ne 0$$ | $$X_{new} = X^{\lambda}$$ |
| $$\lambda = 0$$   | $$X_{new} = log(X)$$      |

-   변환 효과

|               $$\lambda$$ | 효과                                                                           |
|--------------------------:|:-------------------------------------------------------------------------------|
| $$\lambda = 0$$(log 변환) | 우측 꼬리의 길이를 줄여, 우측으로 치우치게 분포하도록 변환합니다.              |
|           $$\lambda > 1$$ | 우측 꼬리의 길이를 늘립니다. $\lambda$가 커질수록 우측 꼬리의 길이가 커집니다. |
|       $$0 < \lambda < 1$$ | 우측 꼬리의 길이를 줄여서 우측으로 치우친 형태의 분포로 변환 됩니다.           |
|           $$\lambda < 0$$ | 역수로 변환 됩니다.                                                            |

**[Ex.4]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic λ=[-2, -1, -0.5, 0, 0.5, 1, 1.5, 2]에 따라 Power Transform된 Fare의 분포를 히스토그램으로 출력해봅니다.
:::

※ Remark

::: {style="border: 1px solid #ddd; padding: 10px;"}
$\lambda$가 0인 경우 log변환을 하게되는데 Fare의 최소값이 0이므로,

Fare가 0인 경우가 존재합니다. 이 때 log 변환은 성립하지 않게 됩니다.

이 때, log의 값이 미지수가 되어 버립니다.

이럴 경우 임의의 수를 더하여 0을 log로 취하는 것을 방지합니다.

변환 후 최소값이 0이 되도록 $log(X + 1)$로 변환합니다.
:::

```{R}
library(ggplot2)
library(gridExtra)

# 람다 값 설정합니다.
lams <- c(-2, -1, -0.5, 0, 0.5, 1, 1.5, 2)

# 히스토그램을 그리기 위한 빈 리스트입니다.
plots <- list()

# 각 람다 값에 대해 히스토그램 생성합니다.
for (lam in lams) {
  if (lam != 0) {
    df_titanic$transformed_Fare <- df_titanic$Fare ^ lam
    p <- ggplot(df_titanic, aes(x = transformed_Fare)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle(paste("lambda =", lam)) +
      theme_minimal()
  } else {
    df_titanic$transformed_Fare <- log(df_titanic$Fare + 1)
    p <- ggplot(df_titanic, aes(x = transformed_Fare)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle("lambda = 0") +
      theme_minimal()
  }
  plots[[length(plots) + 1]] <- p
}

# 여러 히스토그램을 하나의 그래프에 배치합니다.
grid.arrange(grobs = plots, ncol = 4)
```

**[Ex.5]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic λ=[-2, -1, -0.5, 0, 0.5, 1, 1.5, 2]에 따라 Power Transform된 Age의 분포를 히스토그램으로 출력해봅니다.

이 때 Age의 결측치는 제외합니다.
:::

```{R}
library(ggplot2)
library(gridExtra)

# 람다 값 설정합니다.
lams <- c(-2, -1, -0.5, 0, 0.5, 1, 1.5, 2)

# 히스토그램을 그리기 위한 빈 리스트입니다.
plots <- list()

# 각 람다 값에 대해 히스토그램 생성합니다.
for (lam in lams) {
  if (lam != 0) {
    df_titanic$transformed_Age <- df_titanic$Age ^ lam
    p <- ggplot(df_titanic, aes(x = transformed_Age)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle(paste("lambda =", lam)) +
      theme_minimal()
  } else {
    df_titanic$transformed_Age <- log(df_titanic$Age)
    p <- ggplot(df_titanic, aes(x = transformed_Age)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle("lambda = 0") +
      theme_minimal()
  }
  plots[[length(plots) + 1]] <- p
}

# 여러 히스토그램을 하나의 그래프에 배치합니다.
grid.arrange(grobs = plots, ncol = 4)
```

### Box-Cox 변환(Box-Cox Transformation)

-   Power Transformation을 기반으로한 변환으로 정규 분포에 가까운 형태(정규 분포를 따르게 되는 것은 보장하지 않습니다.)로 변환합니다.

-   $\lambda$에 따라 변환함수가 달라집니다. 데이터에서 정규분포와 가깝게 해주는 $\lambda$를 찾아줍니다

| $$\lambda$$       | 거듭 제곱 함수                                      |
|-------------------|-----------------------------------------------------|
| $$\lambda \ne 0$$ | $$X^{(\lambda)} = \frac{X^{\lambda} - 1}{\lambda}$$ |
| $$\lambda = 0$$   | $$X_{new} = log(X)$$                                |

-   $\lambda$는 아래의 손실 함수를 사용하여 구해집니다.

> $l(\lambda) = -\frac{n}{2}ln\left( \frac{1}{n}\sum_{j=1}^n\left( x_j^{(\lambda)} - \bar{x_j}^{(\lambda)}\right)^2 \right) + (\lambda - 1)\sum_{j=1}^nx_j$

손실 함수를 최소화하는 $\lambda$를 구하여 변환 합니다.

**[Ex.6]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic λ=[-2, -1, -0.5, 0, 0.5, 1, 2]에 따라 Power Transform된 Age의 분포를 히스토그램으로 출력해봅니다. 이 때 Age의 결측치는 제외합니다.

여기에 box-cox Transformation의 결과까지 추가합니다.
:::

```{R}
library(MASS)
# Age 컬럼의 결측값이 아닌 값 선택
s_age <- df_titanic$Age[!is.na(df_titanic$Age)]

# 람다 값 설정
lams <- c(-3, -2, -1, -0.5, 0, 0.5, 1, 2)

# 히스토그램을 그리기 위한 빈 리스트 생성
plots <- list()

# 각 람다 값에 대해 히스토그램 생성
for (lam in lams) {
  if (lam == -3) {
    pt <- preProcess(data.frame(Age = s_age), method = "BoxCox")
    transformed_age <- predict(pt, data.frame(Age = s_age))$Age
    lambda <- pt$bc$Age$lambda
    print(lambda)
    p <- ggplot(data.frame(transformed_age), aes(x = transformed_age)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle(paste('box-cox, lambda=', lambda)) +
      theme_minimal()
  } else if (lam != 0) {
    transformed_age <- s_age ^ lam
    p <- ggplot(data.frame(transformed_age), aes(x = transformed_age)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle(paste('lambda=', lam)) +
      theme_minimal() 
  } else {
    transformed_age <- log(s_age)
    p <- ggplot(data.frame(transformed_age), aes(x = transformed_age)) +
      geom_histogram(fill = "blue", color = "black", alpha = 0.7) +
      ggtitle('lambda=0') +
      theme_minimal()
  }
  plots[[length(plots) + 1]] <- p
}

# 여러 히스토그램을 하나의 그래프에 배치
grid.arrange(grobs = plots, ncol = 4)
```

## 2. 범주형 데이터

### 가변수화(One-Hot Encoding, 지시변수화)

범주형 변수를 모델에 포함시키기 위해, 각 수준(범주)마다 범주에 해당 여부를 나타내는 하나의 이진 변수를 할당시킵니다.

예를들어, apple, banana, peach 범주들로 구성된 변수 **fruit**을 가변수해봅니다.

+----------------------------------------------------------------------+---+---------------------------------------------------------------------------------------------------------------------------+
| \|fruit\| \|-----\| \|apple\| \|banana\| \|peach\| \|...\| \|apple\| | ▷ | \|fruit_apple\|fruit_banana\|fruit_peach\| \|----\|----\|----\| \|1\|0\|0\| \|0\|1\|0\| \|0\|0\|1\| \|.....\| \|1\|0\|0\| |
+----------------------------------------------------------------------+---+---------------------------------------------------------------------------------------------------------------------------+

**[Ex.7]**

::: {style="border: 1px solid #ddd; padding: 12px; margin-top: 10px;"}
df_titanic에서 Pclass와 Embarked를 가변수화 합니다.

Embarked의 결측은 최빈값으로 대체합니다.

가변수화한 후 새로운 데이터프레임 을 만듭니다.
:::

```{R}
# 더미 변수를 생성하는 함수
dummy_vars <- dummyVars(~ Pclass + Embarked, data = df_titanic)

# 데이터프레임에 더미 변수를 추가
df_titanic_gd <- cbind(df_titanic, predict(dummy_vars, newdata = df_titanic))

# 결과 출력
head(df_titanic_gd)
```
